<a href="https://colab.research.google.com/github/VigneshGowda-97/SRH-EaSTM/blob/main/energy_output.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [2]:
tf.__git_version__

'v2.6.0-0-g919f693420e'

In [3]:
dataset=pd.read_excel('Energyoutput.xlsx')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [4]:
# spliting the data set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
# building ANN
dataset.isnull()


AT      V     AP     RH     PE
0     False  False  False  False  False
1     False  False  False  False  False
2     False  False  False  False  False
3     False  False  False  False  False
4     False  False  False  False  False
...     ...    ...    ...    ...    ...
9563  False  False  False  False  False
9564  False  False  False  False  False
9565  False  False  False  False  False
9566  False  False  False  False  False
9567  False  False  False  False  False

[9568 rows x 5 columns]

In [6]:
ann=tf.keras.models.Sequential()

In [7]:
# add first hidden layer to input layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [8]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [9]:
ann.add(tf.keras.layers.Dense(units=1))

In [12]:
# train the ann 
ann.compile(optimizer='adam',loss='mean_squared_error')

In [13]:
#training the ann model on the training dataset
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 379.2441
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 292.1873
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 227.7293
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 176.5171
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 137.5247
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 107.7656
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 85.7322
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 69.5169
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 58.0885
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 50.9697
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 45.0365
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 41.

In [14]:
y_pred=ann.predict(x_test)
np.set_printoptions(precision=2)
print(y_pred)
print(y_test)
print(y_train)

[[444.42]
 [457.56]
 [472.42]
 ...
 [432.57]
 [441.92]
 [466.41]]
[450.25 457.46 482.8  ... 434.22 440.07 460.91]
[460.73 438.52 482.82 ... 440.99 439.4  475.58]
